###name: Gonzalo
author: Gonzalo
###baseurl: /blog
description: Gonzalo Leyton
github: http://www.github.com/GonzaloLeyton
###twitter: http://www.twitter.com/tronziroquai
###facebook: http://www.facebook.com
linkedin: http://www.linkedin.com/in/GonzaloLeyton
email: gonzaloleytonf[at]gmail.com
###location: 42°2'16"N   70°12'47"W
###disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
